### ISSUE TITLE
Consider removing `sprout-osx-settings::screen_sharing_app` since the `Screen Sharing.app` is spotlight-findable in its default location

### ISSUE THREAD

**Issue by aramprice** [pivotal-sprout/sprout-osx-settings#20]
I believe this recipe existed because it was not possible to launch the `Screen Sharing.app` directly in earlier versions of OS X.

**Comment by wendorf** [comment]
screen_sharing_app was removed in [this commit](https://github.com/pivotal-sprout/sprout-osx-settings/commit/830befabb1c0824cb8d19f404e491c27232cf609)
