### ISSUE TITLE
Consider removing disable_front_row recipe, discontinued since 10.7

### ISSUE THREAD

**Issue by aramprice** [pivotal-sprout/sprout-osx-settings#7]
Front Row was discontinued in [10.7](https://en.wikipedia.org/wiki/Front_Row_(software))

File [recipes/disable_front_row.rb](https://github.com/pivotal-sprout/sprout-osx-settings/blob/master/recipes/disable_front_row.rb)

**Comment by wendorf** [comment]
Removed the recipe. Closing.
