### ISSUE TITLE
Consider removing "enable_assistive_devices" recipe - it appears to be disabled since ~10.6

### ISSUE THREAD

**Issue by aramprice** [pivotal-sprout/sprout-osx-settings#8]
See http://hints.macworld.com/article.php?story=20060203225241914

Also consider that Accessibility now resides under:

 - System Preferences > Security & Privacy > Accessibility

Where access for individual apps can be toggled.

**Comment by wendorf** [comment]
For future references:

If we wish to automate giving individual apps access to control OS X, we
can edit  the sqlite file /Library/Application Support/com.apple.TCC/TCC.db directly (see
[jacobsalmela/tccutil](https://github.com/jacobsalmela/tccutil) for an implementation example).
